name: resizable_panel
description: Resizable panel widget whose size can be saved to more permanent storage
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: any

import_sorter:
  comments: false